// Generate fake sample data for demo purposes

const sampleMessages = [
  "Hey! How's your day going? 😊",
  "Just finished work, so tired!",
  "Want to grab dinner tonight?",
  "That sounds great! What time?",
  "How about 7pm?",
  "Perfect! See you then ❤️",
  "Good morning! Hope you slept well",
  "Morning! I did, thanks for asking",
  "What are your plans for today?",
  "Not much, just relaxing. You?",
  "Same here, maybe watch a movie later",
  "Ooh that sounds fun! What movie?",
  "I'm thinking about watching that new one everyone's talking about",
  "Oh cool! Let me know how it is",
  "Will do! 🎬",
  "Hey, are you free this weekend?",
  "Yeah, what's up?",
  "Want to go hiking?",
  "That sounds amazing! I'd love to",
  "Great! I'll plan the route",
  "Thanks! You're the best 🥰",
  "How was your meeting?",
  "It went well, thanks for asking!",
  "That's awesome! Proud of you",
  "Aww thanks! That means a lot",
  "Of course! You always do great",
  "Just wanted to say I love you ❤️",
  "Love you too! So much",
  "Miss you!",
  "Miss you more!",
  "Can't wait to see you",
  "Me too! Counting down the days",
  "What's for dinner?",
  "Not sure yet, any ideas?",
  "How about pizza?",
  "Pizza sounds perfect!",
  "Great! I'll order it",
  "Thanks! You're the best",
  "Just got home, so tired",
  "Rest up! You deserve it",
  "Thanks! Talk to you tomorrow",
  "Goodnight! Sweet dreams",
  "Goodnight! ❤️",
  "Hey, did you see that news?",
  "Yeah, crazy right?",
  "I can't believe it",
  "Me neither, it's wild",
  "Hope you're doing okay",
  "I am, thanks for checking in",
  "Of course, always here for you",
  "That means everything to me",
  "Just thinking about you",
  "Aww, that's so sweet",
  "What are you up to?",
  "Just reading, you?",
  "Watching TV, nothing exciting",
  "Sounds relaxing!",
  "It is, wish you were here",
  "Me too! Soon",
  "Can't wait",
  "Hey, want to video call?",
  "Sure! Give me 5 minutes",
  "Perfect! I'll be ready",
  "Just finished, ready when you are",
  "Great! Calling now",
  "How's work going?",
  "Pretty good! Busy but manageable",
  "That's good to hear",
  "Thanks! How about you?",
  "Same, keeping busy",
  "Good! Stay strong",
  "Thanks! You too",
  "Just wanted to say hi",
  "Hi! Good to hear from you",
  "Always good to talk to you",
  "Same here!",
  "What's your favorite color?",
  "Blue! What about you?",
  "I love purple",
  "Nice choice!",
  "Thanks!",
  "Want to go for a walk?",
  "That sounds nice! When?",
  "How about now?",
  "Perfect! I'll be ready in 10",
  "Great! See you soon",
  "Hey, are you okay?",
  "Yeah, why?",
  "Just checking, seemed quiet",
  "I'm fine, thanks for caring",
  "Always!",
  "You're the best friend ever",
  "Aww, you too!",
  "What's the weather like?",
  "Beautiful! Sunny and warm",
  "Lucky! It's raining here",
  "Aww, wish I could share the sun",
  "Me too!",
  "Just finished a great book",
  "Oh cool! What was it?",
  "It was a mystery novel",
  "Sounds interesting!",
  "It was! I'll lend it to you",
  "Thanks! I'd love to read it",
  "Hey, did you remember to...",
  "Oh shoot, I forgot!",
  "No worries, I'll remind you",
  "Thanks! You're a lifesaver",
  "Haha, just looking out for you",
  "I appreciate it!",
  "What's your favorite food?",
  "I love sushi!",
  "Me too! We should go sometime",
  "Definitely! This weekend?",
  "Perfect! I'll make reservations",
  "Thanks! You're amazing",
  "Just for you ❤️",
  "How's your family?",
  "They're doing well, thanks!",
  "That's great to hear",
  "How about yours?",
  "All good here too!",
  "Glad to hear it",
  "Just wanted to say good morning",
  "Good morning! Hope you have a great day",
  "Thanks! You too",
  "I will!",
  "Hey, are you busy?",
  "Not really, what's up?",
  "Just wanted to chat",
  "I'm here! What's on your mind?",
  "Nothing specific, just miss you",
  "Miss you too!",
  "What's your favorite season?",
  "I love fall!",
  "Me too! The colors are beautiful",
  "Exactly! And the weather is perfect",
  "Couldn't agree more",
  "Hey, did you get my message?",
  "Yes! Just saw it",
  "Oh good, was worried",
  "No need to worry!",
  "I know, but I do anyway",
  "That's sweet of you",
  "Just because I care",
  "I know, and I appreciate it",
  "What are you doing this weekend?",
  "Not much planned, you?",
  "Same, want to hang out?",
  "I'd love to!",
  "Great! I'll plan something fun",
  "Can't wait!",
  "Hey, I have good news!",
  "Oh? What is it?",
  "I got the job!",
  "That's amazing! Congratulations!",
  "Thanks! I'm so excited",
  "You should be! So proud of you",
  "Thank you! Means a lot",
  "Of course! You deserve it",
  "Just wanted to check in",
  "I'm doing well, thanks!",
  "Good to hear!",
  "How about you?",
  "All good here!",
  "That's great",
  "What's your favorite movie?",
  "That's a tough one!",
  "I know, so many good ones",
  "I think I'd say The Matrix",
  "Great choice!",
  "Thanks! What about you?",
  "I love Inception",
  "Oh that's a good one too!",
  "Right? So mind-bending",
  "Hey, want to play a game?",
  "Sure! What game?",
  "How about trivia?",
  "Sounds fun! Let's do it",
  "Great! I'll start",
  "Ready when you are",
  "What's the capital of France?",
  "Paris!",
  "Correct! Your turn",
  "Okay, what's 2+2?",
  "Haha, 4!",
  "Too easy!",
  "I know, just warming up",
  "Just wanted to say I'm thinking of you",
  "Aww, that's so sweet",
  "Always!",
  "You're the best",
  "No, you are!",
  "We can both be the best",
  "Deal!",
  "Hey, are you awake?",
  "Yeah, what's up?",
  "Just couldn't sleep",
  "Aww, want to talk?",
  "That would be nice",
  "I'm here for you",
  "Thanks, you always are",
  "Of course!",
  "What's your favorite hobby?",
  "I love reading!",
  "Oh cool! What genres?",
  "Mostly fiction and mystery",
  "Nice! I like those too",
  "We have good taste",
  "I think so too!",
  "Hey, did you see that sunset?",
  "Yes! It was gorgeous",
  "Right? So beautiful",
  "One of the best I've seen",
  "Absolutely stunning",
  "Wish you were here to see it",
  "Me too!",
  "Just finished cooking",
  "Oh nice! What did you make?",
  "Pasta with homemade sauce",
  "Sounds delicious!",
  "It was! Wish I could share",
  "Me too!",
  "How's your day been?",
  "Pretty good! Yours?",
  "Same, nothing too exciting",
  "Sometimes that's nice",
  "True! Peaceful days are good",
  "I agree completely",
  "Hey, want to go shopping?",
  "Sure! What do you need?",
  "Just some groceries",
  "I can come with!",
  "That would be great!",
  "When do you want to go?",
  "How about this afternoon?",
  "Perfect! I'll be ready",
  "Great! See you then",
  "Just wanted to say thank you",
  "For what?",
  "For being such a great friend",
  "Aww, you're welcome",
  "You mean a lot to me",
  "You mean a lot to me too",
  "Hey, are you free to talk?",
  "Yeah, always!",
  "Just needed to vent a bit",
  "I'm here, go ahead",
  "Thanks, I appreciate it",
  "Of course, that's what friends are for",
  "What's your favorite memory?",
  "That's hard to choose!",
  "I know, so many good ones",
  "I think our trip last summer",
  "Oh that was amazing!",
  "Right? Best time ever",
  "Definitely! We should do it again",
  "I'd love to!",
  "Just wanted to say goodnight",
  "Goodnight! Sleep well",
  "You too!",
  "Thanks! ❤️",
  "Hey, did you remember our anniversary?",
  "Of course! How could I forget?",
  "Just checking!",
  "I'd never forget that",
  "I know, just teasing",
  "Haha, you got me",
  "What's your dream vacation?",
  "I'd love to go to Japan",
  "Oh that sounds amazing!",
  "Right? The culture, the food",
  "It would be incredible",
  "Maybe we can go together someday",
  "I'd love that!",
  "Hey, are you okay?",
  "Yeah, why do you ask?",
  "You seemed quiet today",
  "Just tired, but I'm fine",
  "Okay, just wanted to make sure",
  "Thanks for caring",
  "Always!",
  "What's your favorite song?",
  "That changes all the time!",
  "Haha, I know the feeling",
  "Right now it's that new one",
  "Oh I love that one too!",
  "Great minds think alike",
  "They sure do!",
  "Just wanted to say I appreciate you",
  "Aww, thank you",
  "You're welcome",
  "I appreciate you too",
  "Thanks!",
  "Hey, want to watch a show together?",
  "Sure! What show?",
  "How about that new series?",
  "Sounds good!",
  "Great! I'll set it up",
  "Perfect!",
  "How's your week been?",
  "Pretty busy but good",
  "That's good to hear",
  "How about yours?",
  "Same, keeping busy",
  "Good! Stay strong",
  "Thanks! You too",
  "Just thinking about you",
  "Aww, that's sweet",
  "Always thinking about you",
  "You're the best",
  "No, you are!",
  "We can both be",
  "Deal!",
  "Hey, did you get home safe?",
  "Yes! Just got in",
  "Good! Was worried",
  "No need to worry, I'm fine",
  "I know, but I do anyway",
  "That's sweet of you",
  "Just care about you",
  "I know, and I appreciate it",
  "What's your favorite book?",
  "That's so hard to choose!",
  "I know, so many good ones",
  "I think I'd say Pride and Prejudice",
  "Classic! Great choice",
  "Thanks! What about you?",
  "I love The Great Gatsby",
  "Oh that's a good one too!",
  "Right? So beautifully written",
  "Absolutely",
  "Hey, want to go for coffee?",
  "I'd love to!",
  "Great! When works for you?",
  "How about tomorrow morning?",
  "Perfect! I'll see you then",
  "Can't wait!",
  "Just wanted to say hi",
  "Hi! Good to hear from you",
  "Always good to talk",
  "Same here!",
  "What's your favorite animal?",
  "I love dogs!",
  "Me too! They're so loyal",
  "Exactly! And so cute",
  "Couldn't agree more",
  "Hey, are you feeling better?",
  "Yes! Much better, thanks",
  "Good! Was worried about you",
  "I know, thanks for checking",
  "Of course! Always here",
  "I appreciate it",
  "What's your favorite dessert?",
  "I love chocolate cake!",
  "Oh that's a good choice",
  "What about you?",
  "I'm partial to ice cream",
  "Also a great choice!",
  "Right? Can't go wrong",
  "Just wanted to say I miss you",
  "Miss you too!",
  "Can't wait to see you",
  "Me too! Soon",
  "I hope so",
  "Hey, did you finish that project?",
  "Yes! Just turned it in",
  "That's great! How do you feel?",
  "Relieved! It was a lot of work",
  "I bet! Proud of you",
  "Thanks! Means a lot",
  "Of course!",
  "What's your favorite place?",
  "I love the beach!",
  "Oh me too! So peaceful",
  "Right? The sound of waves",
  "Exactly! So relaxing",
  "We should go sometime",
  "I'd love that!",
  "Hey, want to go for a run?",
  "Sure! When?",
  "How about this evening?",
  "Perfect! I'll be ready",
  "Great! See you then",
  "Just wanted to check in",
  "I'm doing well, thanks!",
  "Good to hear!",
  "How about you?",
  "All good here!",
  "That's great",
  "What's your favorite quote?",
  "That's a tough one!",
  "I know, so many good ones",
  "I think 'Be yourself' is great",
  "Simple but powerful",
  "Exactly!",
  "Hey, are you busy tomorrow?",
  "Not really, why?",
  "Want to hang out?",
  "I'd love to!",
  "Great! I'll plan something",
  "Can't wait!",
  "Just wanted to say thank you",
  "For what?",
  "For everything",
  "Aww, you're welcome",
  "You mean the world to me",
  "You do too!",
  "Hey, did you see that?",
  "See what?",
  "That amazing thing that happened",
  "Oh yes! Crazy right?",
  "I know! Can't believe it",
  "Me neither",
  "What's your favorite memory with me?",
  "That's impossible to choose!",
  "Haha, I know",
  "There are so many",
  "I feel the same way",
  "All of them are special",
  "Exactly!",
  "Hey, want to video call?",
  "Sure! Give me a minute",
  "Perfect! I'll be ready",
  "Just finished, ready when you are",
  "Great! Calling now",
  "How's your day going?",
  "Pretty good! Yours?",
  "Same, nothing too exciting",
  "Sometimes that's nice",
  "True!",
  "Just wanted to say I love you",
  "Love you too!",
  "So much",
  "Me too!",
  "Hey, are you okay?",
  "Yeah, why?",
  "Just checking",
  "I'm fine, thanks",
  "Good!",
  "What's your favorite thing about today?",
  "Talking to you!",
  "Aww, that's so sweet",
  "It's true!",
  "You're the best",
  "No, you are!",
  "Hey, want to go somewhere?",
  "Sure! Where?",
  "How about the park?",
  "Sounds nice!",
  "Great! Let's go",
  "Perfect!",
  "Just wanted to say good morning",
  "Good morning!",
  "Hope you have a great day",
  "Thanks! You too",
  "I will!",
  "What's your favorite season?",
  "I love spring!",
  "Oh nice! Why?",
  "Everything's blooming and fresh",
  "That's beautiful",
  "Right? So peaceful",
  "Hey, did you get my text?",
  "Yes! Just saw it",
  "Oh good",
  "Sorry for the delay",
  "No worries!",
  "What's your favorite food?",
  "I love pizza!",
  "Me too! Classic choice",
  "Can't go wrong with pizza",
  "Absolutely!",
  "Just wanted to say I'm thinking of you",
  "Aww, that's sweet",
  "Always!",
  "You're the best",
  "No, you are!",
  "Hey, are you free?",
  "Yeah, what's up?",
  "Just wanted to chat",
  "I'm here!",
  "Thanks!",
  "Of course!",
  "What's your favorite color?",
  "I love green!",
  "Oh nice! Why?",
  "It's so calming",
  "I can see that",
  "Right?",
  "Hey, want to do something fun?",
  "Sure! What?",
  "How about we go explore?",
  "Sounds adventurous!",
  "I think so too!",
  "Let's do it",
  "Just wanted to say thank you",
  "For what?",
  "For being you",
  "Aww, you're welcome",
  "You're amazing",
  "So are you!",
  "Hey, did you remember?",
  "Remember what?",
  "Our plans for today",
  "Oh yes! Of course",
  "Just checking!",
  "Haha, I got you",
  "What's your favorite thing to do?",
  "Spending time with you!",
  "Aww, that's so sweet",
  "It's true!",
  "You're the best",
  "No, you are!",
  "Hey, are you okay?",
  "Yeah, why?",
  "Just wanted to check",
  "I'm fine, thanks",
  "Good!",
  "What's your favorite memory?",
  "All of them with you!",
  "Aww, that's so sweet",
  "It's true!",
  "You're amazing",
  "So are you!",
  "Just wanted to say goodnight",
  "Goodnight!",
  "Sleep well",
  "You too!",
  "Thanks! ❤️"
]

const sampleEmojis = ['❤️', '😊', '🥰', '😍', '😘', '💕', '✨', '🌟', '💖', '😄', '🙂', '😁', '🎉', '🎊', '💯', '🔥', '👍', '👏', '🙌', '💪']

function getRandomElement<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)]
}

function getRandomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

export function generateSampleData() {
  const now = new Date()
  const sixMonthsAgo = new Date(now)
  sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6)
  
  const messages: Array<{
    date: Date
    text: string
    isFromMe: boolean
    wordCount: number
    hour: number
    dayOfWeek: number
    dayName: string
    weekKey: string
    monthKey: string
    sentiment: number
  }> = []
  
  // Generate ~500 messages over the past 6 months
  const numMessages = 500
  const timeRange = now.getTime() - sixMonthsAgo.getTime()
  
  for (let i = 0; i < numMessages; i++) {
    // Random time within the past 6 months
    const randomTime = sixMonthsAgo.getTime() + Math.random() * timeRange
    const date = new Date(randomTime)
    
    // Alternate between you and them, but with some randomness
    const isFromMe = Math.random() > 0.45 // Slightly more messages from "them"
    
    // Get a random message, sometimes add emoji
    let text = getRandomElement(sampleMessages)
    if (Math.random() > 0.7) {
      text += ' ' + getRandomElement(sampleEmojis)
    }
    
    const hour = date.getHours()
    const dayOfWeek = date.getDay()
    const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
    const dayName = dayNames[dayOfWeek]
    
    const wordCount = text.match(/\b\w+\b/g)?.length || 0
    
    // Week key
    const year = date.getFullYear()
    const startOfYear = new Date(year, 0, 1)
    const days = Math.floor((date.getTime() - startOfYear.getTime()) / (24 * 60 * 60 * 1000))
    const week = Math.floor(days / 7)
    const weekKey = `${year}-W${String(week).padStart(2, '0')}`
    
    const monthKey = `${year}-${String(date.getMonth() + 1).padStart(2, '0')}`
    
    // Simple sentiment (slightly positive on average)
    const sentiment = (Math.random() - 0.3) * 0.6 // Range roughly -0.3 to 0.3, slightly positive
    
    messages.push({
      date,
      text,
      isFromMe,
      wordCount,
      hour,
      dayOfWeek,
      dayName,
      weekKey,
      monthKey,
      sentiment
    })
  }
  
  // Sort by date
  messages.sort((a, b) => a.date.getTime() - b.date.getTime())
  
  return messages
}

